#!/usr/bin/env python3
"""Embed the companion's authoritative protocol and shared native fixtures."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RESOURCE = Path("companion/src/cph_ai_companion/resources/protocol")


def unique_members(pairs: list[tuple[str, object]]) -> dict:
    members = {}
    for key, value in pairs:
        if key in members:
            raise ValueError(f"duplicate JSON member: {key}")
        members[key] = value
    return members


def reject_constant(value: str) -> None:
    raise ValueError(f"non-finite JSON constant: {value}")


def read_json(path: Path) -> tuple[bytes, object]:
    raw = path.read_bytes()
    value = json.loads(raw, object_pairs_hook=unique_members,
                       parse_constant=reject_constant)
    return raw, value


def render_header(root: Path) -> str:
    protocol_path = RESOURCE / "protocol.json"
    fixtures_path = RESOURCE / "fixtures.json"
    raw, spec = read_json(root / protocol_path)
    fixture_raw, fixtures = read_json(root / fixtures_path)
    if (not isinstance(spec, dict) or
            type(spec.get("schema_version")) is not int or
            spec["schema_version"] != 1 or
            spec.get("protocol_version") not in ("1.0", "1.1")):
        raise ValueError("unsupported protocol schema or version")
    if not isinstance(fixtures, list) or not fixtures:
        raise ValueError("shared fixtures must be a nonempty array")
    names = set()
    for fixture in fixtures:
        if (not isinstance(fixture, dict) or
                not isinstance(fixture.get("name"), str) or
                not fixture["name"] or fixture["name"] in names or
                type(fixture.get("valid")) is not bool or
                "plan" not in fixture):
            raise ValueError("invalid or duplicate shared fixture metadata")
        names.add(fixture["name"])
    encoded = json.dumps(spec, ensure_ascii=True, separators=(",", ":"))
    fixture_encoded = json.dumps(fixtures, ensure_ascii=True,
                                 separators=(",", ":"))
    if ')CPHAI"' in encoded or ')CPHAIFIX"' in fixture_encoded:
        raise ValueError("invalid raw-string delimiter")
    return "\n".join([
        "// Generated by tools/actor_control/generate_protocol.py. "
        "Do not edit.",
        "// SHA-256 values identify the authoritative input bytes.",
        "#pragma once",
        "namespace cata::actor_control {",
        'inline constexpr char protocol_source_path[] = "' +
        protocol_path.as_posix() + '";',
        'inline constexpr char protocol_fixtures_source_path[] = "' +
        fixtures_path.as_posix() + '";',
        'inline constexpr char protocol_version[] = "' +
        spec["protocol_version"] + '";',
        'inline constexpr char protocol_digest[] = "' +
        hashlib.sha256(raw).hexdigest() + '";',
        'inline constexpr char protocol_fixtures_digest[] = "' +
        hashlib.sha256(fixture_raw).hexdigest() + '";',
        'inline constexpr char protocol_json[] = R"CPHAI(' +
        encoded + ')CPHAI";',
        'inline constexpr char protocol_fixtures_json[] = R"CPHAIFIX(' +
        fixture_encoded + ')CPHAIFIX";',
        "}",
        "",
    ])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "src/actor_control_protocol_generated.h"
    try:
        content = render_header(ROOT)
        if args.check:
            if (not output.is_file() or
                    output.read_text(encoding="utf-8") != content):
                parser.error("generated protocol header is stale")
        else:
            output.write_text(content, encoding="utf-8")
    except (OSError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
