#!/usr/bin/env python3
"""Generate the native embedded contract from its fixed source snapshot."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    directory = ROOT / "data/reference/actor_control"
    source = json.loads((directory / "source.json").read_text())
    for name, digest in source["files"].items():
        if name not in ("protocol.json", "fixtures.json"):
            parser.error("unexpected snapshot file")
        if hashlib.sha256((directory / name).read_bytes()).hexdigest() != digest:
            parser.error("protocol snapshot fingerprint differs from its source")
    raw = (directory / "protocol.json").read_bytes()
    spec = json.loads(raw)
    encoded = json.dumps(spec, ensure_ascii=True, separators=(",", ":"))
    if ')CPHAI"' in encoded:
        parser.error("invalid raw-string delimiter")
    content = ('// Generated by tools/actor_control/generate_protocol.py. Do not edit.\n'
               '// Authoritative snapshot: cph-ai-companion ' + source["source_revision"] + '\n'
               '#pragma once\n'
               'namespace cata::actor_control {\n'
               'inline constexpr char protocol_version[] = "1.0";\n'
               'inline constexpr char protocol_digest[] = "' + hashlib.sha256(raw).hexdigest() + '";\n'
               'inline constexpr char protocol_json[] = R"CPHAI(' + encoded + ')CPHAI";\n'
               '}\n')
    output = ROOT / "src/actor_control_protocol_generated.h"
    if args.check:
        if not output.is_file() or output.read_text() != content:
            parser.error("generated protocol header is stale")
    else:
        output.write_text(content)


if __name__ == "__main__":
    main()
