#!/usr/bin/env python3
"""Generate the C++ built-in mod ID manifest used by runtime validation."""

import argparse
import json
from pathlib import Path
import sys


def strip_jsonc_comments(text: str) -> str:
    """Remove // and /* */ comments while preserving quoted strings."""
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False

    while index < len(text):
        char = text[index]
        next_char = text[index + 1] if index + 1 < len(text) else ""
        if in_string:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
        elif char == '"':
            in_string = True
            result.append(char)
            index += 1
        elif char == "/" and next_char == "/":
            index += 2
            while index < len(text) and text[index] not in "\r\n":
                index += 1
        elif char == "/" and next_char == "*":
            index += 2
            while index + 1 < len(text) and not (
                text[index] == "*" and text[index + 1] == "/"
            ):
                if text[index] in "\r\n":
                    result.append(text[index])
                index += 1
            index += 2
        else:
            result.append(char)
            index += 1
    return "".join(result)


def strip_trailing_commas(text: str) -> str:
    """Remove commas before a closing JSON array or object."""
    result: list[str] = []
    index = 0
    in_string = False
    escaped = False

    while index < len(text):
        char = text[index]
        if in_string:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            index += 1
            continue
        if char == '"':
            in_string = True
            result.append(char)
            index += 1
            continue
        if char == ",":
            lookahead = index + 1
            while lookahead < len(text) and text[lookahead].isspace():
                lookahead += 1
            if lookahead < len(text) and text[lookahead] in "]}":
                index += 1
                continue
        result.append(char)
        index += 1
    return "".join(result)


def find_mod_ids(value: object, path: Path) -> set[str]:
    result: set[str] = set()
    if isinstance(value, dict):
        entries = [value]
    elif isinstance(value, list):
        entries = value
    else:
        raise ValueError(f"{path}: expected array or object")

    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError(f"{path}: modinfo array entry is not an object")
        if entry.get("type") == "MOD_INFO":
            mod_id = entry.get("id")
            if not isinstance(mod_id, str) or not mod_id:
                raise ValueError(f"{path}: MOD_INFO has no string id")
            result.add(mod_id)
    return result


def cxx_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def find_mod_roots(source: Path) -> set[str]:
    """Return packaged top-level roots containing legacy or Platform Mods."""
    result: set[str] = set()
    for child in source.iterdir():
        if not child.is_dir():
            continue
        if (
            (child / "main.lua").is_file() or
            (child / "mod.lua").is_file() or
            any(child.rglob("modinfo.json"))
        ):
            result.add(child.relative_to(source).as_posix())
    return result


def write_header(
    output: Path,
    available: bool,
    mod_ids: list[str],
    mod_roots: list[str],
    *,
    check: bool = False,
) -> bool:
    entries = ",\n".join(f"    {cxx_string(mod_id)}" for mod_id in mod_ids)
    roots = ",\n".join(f"    {cxx_string(root)}" for root in mod_roots)
    availability = "true" if available else "false"
    content = (
        "// This file is generated by tools/generate_builtin_mods.py.\n"
        "#pragma once\n"
        "#ifndef CATA_SRC_BUILTIN_MODS_GENERATED_H\n"
        "#define CATA_SRC_BUILTIN_MODS_GENERATED_H\n\n"
        "#include <array>\n"
        "#include <string_view>\n\n"
        f"constexpr bool builtin_mod_manifest_available = {availability};\n"
        "constexpr std::array<std::string_view, "
        f"{len(mod_ids)}> builtin_mod_ids = {{\n"
        f"{entries}\n"
        "};\n"
        "constexpr std::array<std::string_view, "
        f"{len(mod_roots)}> builtin_mod_roots = {{\n"
        f"{roots}\n"
        "};\n\n"
        "#endif // CATA_SRC_BUILTIN_MODS_GENERATED_H\n"
    )
    if output.is_file() and output.read_text(encoding="utf-8") == content:
        return True
    if check:
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the generated header is stale",
    )
    args = parser.parse_args()

    if not args.source.is_dir():
        print(
            f"Built-in mod directory does not exist: {args.source}",
            file=sys.stderr,
        )
        current = write_header(
            args.output, False, [], [], check=args.check
        )
        if args.check and not current:
            print(
                f"Built-in Mod manifest is stale: {args.output}",
                file=sys.stderr,
            )
            return 1
        return 0

    try:
        mod_ids: set[str] = set()
        for modinfo in args.source.rglob("modinfo.json"):
            text = modinfo.read_text(encoding="utf-8-sig")
            value = json.loads(
                strip_trailing_commas(strip_jsonc_comments(text))
            )
            mod_ids.update(find_mod_ids(value, modinfo))
        current = write_header(
            args.output,
            True,
            sorted(mod_ids),
            sorted(find_mod_roots(args.source)),
            check=args.check,
        )
    except (OSError, ValueError) as error:
        print(
            f"Unable to generate built-in mod manifest: {error}",
            file=sys.stderr,
        )
        return 1
    if args.check and not current:
        print(
            f"Built-in Mod manifest is stale: {args.output}",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
